### ISSUE TITLE
empty ref on persName with nested rolename

### ISSUE THREAD

**Issue by duncdrum** [readchina/shouchaoben#50]
```xml
<persName ref="#">谢<roleName>部长</roleName>
```

We can fix these manually, but we should make sure that the transformation outputs the desired result, for future conversions.

**Comment by whalekeykeeper** [comment]
I will try to add a predicate or an if-else to set a default `ref` value as `P0000` (and the same for place and org).
If you have better solutions, XD any hints will be appreciated.

**Comment by duncdrum** [comment]
i tend to use element constructor syntax to only generate attributes when an attribute value exists that can be inserted. `P0000` is suboptimal, but better then empty refs. These entries all should have a proper attribute value though, as the linked entities are generated by reading these files in the first place
