### ISSUE TITLE
CSS transform errors with hugo extended version

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/shouchaoben#56]
Hugo local page was built successfully that the correct page can be seen locally.

But the command `hugo` to deploy the page for pushing to remote failed:
```
error: failed to transform resource: TOCSS: failed to transform "scss/main.scss" (text/x-scss): this feature is not available in your current Hugo version
```
Hugo [FAQ](https://gohugo.io/troubleshooting/faq/#i-get-this-feature-is-not-available-in-your-current-hugo-version) says:

> (Q: )I get “… this feature is not available in your current Hugo version” 
> (A: )If you process SCSS or Sass to CSS in your Hugo project with libsass as the transpiler or if you convert images to the webp format, you need the Hugo extended version, or else you may see an error message similar to the below:
>
>error: failed to transform resource: TOCSS: failed to transform "scss/main.scss" (text/x-scss): this feature is not available in your current Hugo version
>We release two set of binaries for technical reasons. The extended version is not what you get by default for some installation methods. On the [release page](https://github.com/gohugoio/hugo/releases), look for archives with extended in the name. To build hugo-extended, use go install --tags extended
>
>To confirm, run hugo version and look for the word extended.

After installing go, the `go install --tags extended` couldn't work because go can't find module.
At the end, by installing `npm` and followed the instructions on[ this page](https://www.npmjs.com/package/hugo-extended), `extended` version seems to be installed because `go install` works.
Though `npm run start` is not working, the command `hugo` is working.

At current stage, we have:
```
░▒▓ ~/Doc/G/shouchaoben  main ?6  hugo                    1 ✘  02:50:47 ▓▒░
Start building sites … 
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown

                   | EN | DE  
-------------------+----+-----
  Pages            |  9 |  7  
  Paginator pages  |  0 |  0  
  Non-page files   |  0 |  0  
  Static files     | 35 | 35  
  Processed images |  0 |  0  
  Aliases          |  1 |  0  
  Sitemaps         |  2 |  1  
  Cleaned          |  0 |  0  

Total in 1252 ms
```

Will push to see if the GitHub Action can deploy the page correctly or not.

To record above is aiming to leave a reminder to probably upgrade Hugo's version or rethink of the theme.

**Comment by whalekeykeeper** [comment]
@duncdrum The last commit I am pushing was under pushing for more than 30 minutes that I need to go to sleep now. Therefore I can't check right now if the website is deployed successful or not. But it should not be far away from that.

**Comment by whalekeykeeper** [comment]
Uh the push finished.
CI failed and the error is:
```
Error: Error building site: POSTCSS: failed to transform "css/main.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

From the GitHub page of our theme, I found this [discussion](https://github.com/victoriadrake/hugo-theme-introduction/issues/210) , I went to check our package.json, it looks fine...

**Comment by whalekeykeeper** [comment]
Also tried the [solution](https://discourse.gohugo.io/t/error-deploying-on-render-check-your-post-css-installation/40810/2) of adding a `postcss.config.js` file but it doesn't work.

**Comment by duncdrum** [comment]
Can you open a draft PR please
