### ISSUE TITLE
Edit the landing page of Shouchaoben

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/shouchaoben#65]
see [issue 306](https://github.com/readchina/readchina.github.io/issues/306) and[ issue 307](https://github.com/readchina/readchina.github.io/issues/307) of readchina.github.io

**Comment by whalekeykeeper** [comment]
After the edit, now it roughly looks like:

<img width="843" alt="Screenshot 2023-12-17 at 03 56 08" src="https://github.com/readchina/shouchaoben/assets/46596921/0885ad9c-7dda-4664-890f-fc3ea828e69a">

<img width="784" alt="Screenshot 2023-12-17 at 03 56 33" src="https://github.com/readchina/shouchaoben/assets/46596921/3070540e-2f30-45e0-96ab-d08f9f2d6c2d">

<img width="801" alt="Screenshot 2023-12-17 at 03 58 27" src="https://github.com/readchina/shouchaoben/assets/46596921/a5ecd6ab-f04b-4f6f-a5f2-df698d71ea5b">

<img width="808" alt="Screenshot 2023-12-17 at 04 00 08" src="https://github.com/readchina/shouchaoben/assets/46596921/7d970432-e987-4d67-8bfc-5953a738bae9">

**Comment by whalekeykeeper** [comment]
Hi @LenaHenningsen , may you have a look? 
Either just look at the screenshots, or clone this repository and run `hugo server` in the terminal to do local building

**Comment by LenaHenningsen** [comment]
This looks truly beautiful, thank you so much! 
I would have three minor changes to request:
- The reference to Zhao Zhenkai's Waves: please italicize Waves, and delete the _ _ before and after it.
- can you add (transcriptions) behind Xiayin's name?
- and as a contact email lena.henningsen@zo.uni-heidelberg.de
Thanks a lot!!!
Lena

**Comment by whalekeykeeper** [comment]
> This looks truly beautiful, thank you so much! I would have three minor changes to request:
> 
> * The reference to Zhao Zhenkai's Waves: please italicize Waves, and delete the _ _ before and after it.
> * can you add (transcriptions) behind Xiayin's name?
> * and as a contact email [lena.henningsen@zo.uni-heidelberg.de](mailto:lena.henningsen@zo.uni-heidelberg.de)
>   Thanks a lot!!!
>   Lena

All the listed parts are modified accordingly. Would be lovely if you have the time to review the new PR #66
